version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379
    volumes:
      - ./redis_data:/data
  whatsapp-chat:
    container_name: whatsapp-chat
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: bridge
    env_file:
      - .env
    ports:
      - 8080:8080
    links:
      - redis
    volumes:
      - .:/app
volumes:
  redis_data:
    driver: local
# 1 Run compose file for build :- docker-compose up --build -d
# 2 Stop compose file :- docker-compose down
# 3 Docker logs :- docker logs container-id
# 4 Docker stop :- docker stop
# 5 Docker remove :- docker rm container-id
